jwt:
  authExpirationMs: 3600000
  refreshExpirationMs: 86400000
  password-reset-expiration-days: 2
  email-verification-expiration-days: 5

server:
  port: 9002
spring:
  application:
    name: auth-service
  profiles:
    active: mongo
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true


eureka:
  client:
    enabled: true

    fetch-registry: true
    register-with-eureka: true


auth:
  settings:
    sign-in:
      only-admins-can-create-users: true
      require-admin-validation: false
      require-email-validation: true
      account-activation: none
    user-role-endpoint:
      enabled: true
    identity: email
    roles:
      - ROLE_USER
      - ROLE_ADMIN
    event-broker: internal

kafka:
  securityProtocol: SASL_SSL
  saslMechanism: SCRAM-SHA-512
  retry-backoff-in-ms: 100
  retries: 5
  ssl:
    #    keyStore: ${server.ssl.keystore}
    #    keyStoreType: ${server.ssl.keystoretype}
    #    keyStorePassword: ${server.ssl.keystorepassword}
    #    keyPassword: ${server.ssl.keypassword}
    #    trustStore: ${server.ssl.truststore}
    #    trustStorePassword: ${server.ssl.truststorepassword}
    #    trustStoreType: ${server.ssl.truststoretype}
    enabled: false


management:
  health:
    defaults:
      enabled: false
    mongo:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "health,info"
