spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth
  datasource:
    url: jdbc:mysql://localhost:3309/auth
    username: root
    password: root

server:
  tomcat:
    accesslog:
      enabled: false

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  token:
    secretKey: '614E645267556B58703273357638792F413F4428472B4B6250655368566D597133743677397A244326452948404D635166546A576E5A7234753778214125442A'



auth:
  settings:
    sign-in:
      account-activation: VERIFY_EMAIL
    admin-roles:
      - ROLE_ADMIN
    roles:
      - ROLE_DEVELOPER
      - ROLE_PRINCIPLE
      - ROLE_EDITOR



kafka:
  producer:
    bootstrap-servers: localhost:29092
    security-protocol: PLAINTEXT
    writeTopicName: outsource-me-api-user-registered
  consumer:
    application-id: auth-service
    bootstrap-servers: localhost:29092
    security-protocol: PLAINTEXT
    topic:
      registration-failed-topic: outsource-me-api-registration-failed
