server:
  port: 9002
  tomcat:
    accesslog:
      max-days: 5
      directory: log/access
      enabled: true
spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  config:
    import:
      - "auth-core.yaml"
      - "optional:auth-kafka.yaml"
      - "optional:auth-mongodb.yaml"
      - "optional:auth-mysql.yaml"

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true

management:
  health:
    defaults:
      enabled: false
    mongo:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "health,info"


logging:
  logback:
    rollingpolicy:
      max-history: 5
    compression-type: zip
